default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: to_do_test_app_development

  <<: *default
  database: to_do_test_app_test


production:
  <<: *default
  database: to_do_test_app_production
